
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:  # to allow manual re-runs


jobs:
  linting:
    name: "Perform linting checks"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-python@v4"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip poetry
          poetry install
      - name: "Run pyupgrade"
        run: |
          poetry run pre-commit run pyupgrade --all-files
      - name: "Code formating (black)"
        run: |
          poetry run pre-commit run black --all-files
      - name: "Code formating (flake8)"
        run: |
          poetry run pre-commit run flake8 --all-files
      - name: "Order of imports (isort)"
        run: |
          poetry run pre-commit run isort --all-files
      - name: "Typing checks (mypy)"
        run: |
          poetry run pre-commit run mypy --all-files
      - name: "Run trailing-whitespace"
        run: |
          poetry run pre-commit run trailing-whitespace --all-files
      - name: "Run end-of-file-fixer"
        run: |
          poetry run pre-commit run end-of-file-fixer --all-files
      - name: "Run check-docstring-first"
        run: |
          poetry run pre-commit run check-docstring-first --all-files
      - name: "Run debug-statements"
        run: |
          poetry run pre-commit run debug-statements --all-files
      - name: "Run check-ast"
        run: |
          poetry run pre-commit run check-ast --all-files
